include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - flutter/packages/flutter_tools/test/**
    - flutter/bin/cache/**
    - flutter/examples/**
    - flutter/packages/flutter_tools/test/widget_preview_scaffold.shard/**
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_single_quotes
    - always_declare_return_types
    - require_trailing_commas